sudo: required
dist: xenial
language: python
matrix:
  include:
    - python: 3.6
    - python: 3.7
before_install:
  - sudo apt-get install pandoc
install:
  - pip install -e .[dev]
before_script:
  - black --check report
  - isort report --check-only
script:
  - pytest report --cov=ross
after_success:
  - codecov
deploy:
  provider: pypi
  user: GabrielBachmann
  password:
    secure: "e0Sz0lg7DX4wn2dxG79pkvZwXItGqUeu2K91DlvrF9OhX8zOILIGir5O6+OCqAt9HreVYGj3IN7LmFIoityXopaJve9gOhwgbfRhSvvx1p+2r4+Cghlo7++5AqN74wzU+Mi0PcSFWyr0RUEUHjyJA9FrKU0JwZv1OKj5DqTQcrSP8AAiKQ/T2ys3GJvfnHR/NHOKs5yXQ2u1vZIyeILKCFlLjTn//b45cfF6hxHZDdLPFz+44EyHzc+RcYAHA1fpEFHhl7RoxvkwSDwVAiOsVTMuPko2ZjJ66EfHyzQafgHSQw7PHC1CRHF5Oj1vGwxNOM9uKar+94WFRZIXbZ6bduneD4cqYnBiClgHiUqAazCgfrArl/tfxlpH0NXjmRbwEwDbBNjiW+Mtz3XGQTj1ZPAlyi3+sviUpJcQ65PWMSKu153Z9mdYg/G1JotEDg9qbb7Ykc8IvcQWZ2lhyJrVpUefsp1njG5Sj8MoVu02cxYI2wp/Xgjmkh2i25nuRYZ9Ja5dwPUaE5bkDk8iCqj6YsOYWzdbOeWHFBvNeSEHtN4KI2xftoYI32lzzg8Zig2D/fqq+/6mBro25szrZnen3jbYaHe6BatneKCB8bNw3gjjH+B9ByeXyfuFPBc9gvWmFssia+8203H3h1QzGpS2ui5Y4QV9UOK7pauemGtCRko="
  on:
    tags: true
    python: 3.7
